language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - pip install pipenv
  - pipenv sync

  # install theme
  - wget https://github.com/ssoi/taman/archive/master.zip
  - unzip master.zip

  # initialize and update submodules
  - git submodule init
  - git submodule update

before_script:
  - pelican-themes --install taman-master --verbose

script: THEMEDIR="taman-master" make html

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: sameersoi.com/
  local_dir: output/
