language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # install pelican and markdown
  - conda install -c conda-forge pelican
  - conda install -c anaconda markdown

  # install theme
  - wget -O /tmp/master.zip https://github.com/ssoi/taman/archive/master.zip
  - cd /tmp/; unzip master.zip

before_script:
  - pelican-themes --install /tmp/taman-master --verbose

script:
  - THEMEDIR="/tmp/taman-master" make html

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: THEMEDIR="/tmp/taman-master" make publish
#    on:
#      branch: master
