version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
    build:
        docker:
            - image: circleci/python:3.7.9
              auth:
                username: mydockerhub-user
                password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
            - run:
                  name: Build Pipenv Virtual Environment
                  command: |
                      pip install pipenv
                      pipenv sync
            - run:
                  name: Initialize and update submodules
                  command: |
                      git submodule init
                      git submodule update
            - run:
                  name: Download and install theme
                  command: |
                      wget https://github.com/ssoi/pelican-blue/archive/master.zip
                      unzip master.zip
                      pipenv run pelican-themes --install pelican-blue-master --verbose
            - run:
                  name: Create content
                  command: |
                    THEMEDIR="pelican-blue-master" pipenv run make html
            - aws-s3/sync:
                  arguments: |
                      --acl public-read \
                      --cache-control "max-age=86400"
                  from: output
                  to: 's3://sameersoi.com/'
workflows:
  main:
    jobs:
      - build
