version: 2.1

jobs:
    build:
        docker:
            - image: circleci/python:3.7.9
              auth:
                username: mydockerhub-user
                password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
            - run:
                  name: Build Pipenv Virtual Environment
                  command: |
                      pip install pipenv
                      pipenv sync
            - run:
                  name: Initialize and update submodules
                  command: |
                      git submodule init
                      git submodule update
            - run:
                  name: Download and install theme
                  command: |
                      wget https://github.com/ssoi/taman/archive/master.zip
                      unzip master.zip
                      pelican-themes --install taman-master --verbose
            - run:
                  name: Create content
                  command: THEMEDIR="taman-master" make html
workflows:
  main:
    jobs:
      - build
