version: 2.1

jobs:
    build:
        docker:
            - image: circleci/python:3.7.9
              auth:
                username: mydockerhub-user
                password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
            - run:
                  name: Build Pipenv Virtual Environment
                  command: |
                      pip install pipenv
                      pipenv sync
workflows:
  main:
    jobs:
      - build
